// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeNbyBYtTbAUn0owmzQ2ETb6xs6ZuvHLg',
    appId: '1:695679791383:web:1c8021d7fe07e74f978752',
    messagingSenderId: '695679791383',
    projectId: 'campus-notify-tugas',
    authDomain: 'campus-notify-tugas.firebaseapp.com',
    storageBucket: 'campus-notify-tugas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBznl9hNz51fplANeIP4AJGn9dmLJIETV0',
    appId: '1:695679791383:android:c071c03b57f2c793978752',
    messagingSenderId: '695679791383',
    projectId: 'campus-notify-tugas',
    storageBucket: 'campus-notify-tugas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtDTnvGEkOuMHr--bvVpGgEj02t2MYSNI',
    appId: '1:695679791383:ios:9f92fa36bcc6b89e978752',
    messagingSenderId: '695679791383',
    projectId: 'campus-notify-tugas',
    storageBucket: 'campus-notify-tugas.firebasestorage.app',
    iosBundleId: 'com.example.week6Tugas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtDTnvGEkOuMHr--bvVpGgEj02t2MYSNI',
    appId: '1:695679791383:ios:9f92fa36bcc6b89e978752',
    messagingSenderId: '695679791383',
    projectId: 'campus-notify-tugas',
    storageBucket: 'campus-notify-tugas.firebasestorage.app',
    iosBundleId: 'com.example.week6Tugas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeNbyBYtTbAUn0owmzQ2ETb6xs6ZuvHLg',
    appId: '1:695679791383:web:3923893f6d62b8f5978752',
    messagingSenderId: '695679791383',
    projectId: 'campus-notify-tugas',
    authDomain: 'campus-notify-tugas.firebaseapp.com',
    storageBucket: 'campus-notify-tugas.firebasestorage.app',
  );
}
