// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAAbbuoe7xzKRVtl29FKiAKkDt7bNJ9-o',
    appId: '1:298507654145:web:0f228bb99d4e9bd8bfdc00',
    messagingSenderId: '298507654145',
    projectId: 'campus-notify-b797b',
    authDomain: 'campus-notify-b797b.firebaseapp.com',
    storageBucket: 'campus-notify-b797b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdgvcxBsyfjgUmPM_dhkESL_5uCefNlc',
    appId: '1:298507654145:android:f1c60f5c8c370821bfdc00',
    messagingSenderId: '298507654145',
    projectId: 'campus-notify-b797b',
    storageBucket: 'campus-notify-b797b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSAx66T_epI4RHLVv1ITXr3awsn2LFxA',
    appId: '1:298507654145:ios:470f7ebe3a9fdb85bfdc00',
    messagingSenderId: '298507654145',
    projectId: 'campus-notify-b797b',
    storageBucket: 'campus-notify-b797b.firebasestorage.app',
    iosBundleId: 'com.example.campusNotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANSAx66T_epI4RHLVv1ITXr3awsn2LFxA',
    appId: '1:298507654145:ios:470f7ebe3a9fdb85bfdc00',
    messagingSenderId: '298507654145',
    projectId: 'campus-notify-b797b',
    storageBucket: 'campus-notify-b797b.firebasestorage.app',
    iosBundleId: 'com.example.campusNotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAAbbuoe7xzKRVtl29FKiAKkDt7bNJ9-o',
    appId: '1:298507654145:web:c39cef1a4530e35ebfdc00',
    messagingSenderId: '298507654145',
    projectId: 'campus-notify-b797b',
    authDomain: 'campus-notify-b797b.firebaseapp.com',
    storageBucket: 'campus-notify-b797b.firebasestorage.app',
  );
}
